package com.madrigalsolu.nuestrodia.compose.theme

import androidx.compose.ui.graphics.Color

// Light Color Scheme Tokens
val PrimaryLight = Color(0xFF8F4C38)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFFFDBD1)
val OnPrimaryContainerLight = Color(0xFF723523)
val SecondaryLight = Color(0xFF77574E)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFFFDBD1)
val OnSecondaryContainerLight = Color(0xFF5D4037)
val TertiaryLight = Color(0xFF6C5D2F)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFF5E1A7)
val OnTertiaryContainerLight = Color(0xFF534619)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF93000A)
val BackgroundLight = Color(0xFFFFF8F6)
val OnBackgroundLight = Color(0xFF231917)
val SurfaceLight = Color(0xFFFFF8F6)
val OnSurfaceLight = Color(0xFF231917)
val SurfaceVariantLight = Color(0xFFF5DED8)
val OnSurfaceVariantLight = Color(0xFF53433F)
val OutlineLight = Color(0xFF85736E)
val OutlineVariantLight = Color(0xFFD8C2BC)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFFFF1ED)
val SurfaceContainerLight = Color(0xFFFCEAE5)
val SurfaceContainerHighLight = Color(0xFFF7E4E0)
val SurfaceContainerHighestLight = Color(0xFFF1DFDA)
val InverseSurfaceLight = Color(0xFF392E2B)
val InverseOnSurfaceLight = Color(0xFFFFEDE8)
val InversePrimaryLight = Color(0xFFFFB5A0)

// Dark Color Scheme Tokens
val PrimaryDark = Color(0xFFFFB5A0)
val OnPrimaryDark = Color(0xFF561F0F)
val PrimaryContainerDark = Color(0xFF723523)
val OnPrimaryContainerDark = Color(0xFFFFDBD1)
val SecondaryDark = Color(0xFFE7BDB2)
val OnSecondaryDark = Color(0xFF442A22)
val SecondaryContainerDark = Color(0xFF5D4037)
val OnSecondaryContainerDark = Color(0xFFFFDBD1)
val TertiaryDark = Color(0xFFD8C58D)
val OnTertiaryDark = Color(0xFF3B2F05)
val TertiaryContainerDark = Color(0xFF534619)
val OnTertiaryContainerDark = Color(0xFFF5E1A7)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF1A110F)
val OnBackgroundDark = Color(0xFFF1DFDA)
val SurfaceDark = Color(0xFF1A110F)
val OnSurfaceDark = Color(0xFFF1DFDA)
val SurfaceVariantDark = Color(0xFF53433F)
val OnSurfaceVariantDark = Color(0xFFD8C2BC)
val OutlineDark = Color(0xFFA08C87)
val OutlineVariantDark = Color(0xFF53433F)
val SurfaceContainerLowestDark = Color(0xFF140C0A)
val SurfaceContainerLowDark = Color(0xFF231917)
val SurfaceContainerDark = Color(0xFF271D1B)
val SurfaceContainerHighDark = Color(0xFF322825)
val SurfaceContainerHighestDark = Color(0xFF3D322F)
val InverseSurfaceDark = Color(0xFFF1DFDA)
val InverseOnSurfaceDark = Color(0xFF392E2B)
val InversePrimaryDark = Color(0xFF8F4C38)
